export TMUX_STATUSBAR_BG=colour0
export TMUX_LEFT_SEGMENT_START=
export TMUX_LEFT_SEGMENT_END=
export TMUX_LEFT_SEPARATOR=
export TMUX_RIGHT_SEGMENT_START=
export TMUX_RIGHT_SEGMENT_END=
export TMUX_RIGHT_SEPARATOR=
