# ALL HALLOW'S EVE

# vim/bat config
SYNTAX_THEME=all-hallows-eve-plus
WINTERM_THEME=all-hallows-eve

# tmux config
TMUX_THEME='system-theme'

# segments
PROMPT_LEFT_END=' \\ufb8a' # skull
PROMPT_RIGHT_START='' # the portion proceding user input
PROMPT_RIGHT_END='' # the rightmost side
LEFT_SEGMENT_START='' # '\\uE0B0'
LEFT_SEGMENT_END=''
LEFT_SEPARATOR='\\uE621' # '\\uE0B1'
RIGHT_SEGMENT_START='' # '\\uE0B2'
RIGHT_SEGMENT_END=''
RIGHT_SEPARATOR='\\uE621' # '\\uE0B3'

# colors
BLACK=#212121
RED=#d56600
GREEN=#1aab15
YELLOW=#bdda00
BLUE=#616171
PURPLE=#63007e
CYAN=#c592ff
WHITE=#eeffff
BRIGHT_BLACK=#404040
BRIGHT_RED=#ff9a00
BRIGHT_GREEN=#09ff00
BRIGHT_YELLOW=#d9ff00
BRIGHT_BLUE=#acacd4
BRIGHT_PURPLE=#c900ff
BRIGHT_CYAN=#d57bff
BRIGHT_WHITE=#ffffff

BACKGROUND=#0c0c0c
FOREGROUND=$BRIGHT_WHITE

