# CYBERPUNK

# vim/bat config
SYNTAX_THEME=cyberpunk
AIRLINE_THEME=system

CHROME_THEME=https://chrome.google.com/webstore/detail/cyberpunk/ekkfihjmcoeplagmladakeignpdaecmc

FONT_FACE="Scientifica NF"
FONT_FAMILY="Scientifica Nerd Font"
FONT_STYLE="Normal"
FONT_SIZE=17

# colors
BLACK=#101116
RED=#ff0055
GREEN=#00ff84
YELLOW=#fffc58
BLUE=#00b0ff
PURPLE=#311b92
CYAN=#c592ff
WHITE=#eeffff
BRIGHT_BLACK=#2b3e5a
BRIGHT_RED=#ff1745
BRIGHT_GREEN=#00ffc8
BRIGHT_YELLOW=#b3ff00
BRIGHT_BLUE=#6766b3
BRIGHT_PURPLE=#283593
BRIGHT_CYAN=#d57bff
BRIGHT_WHITE=#ffffff

BACKGROUND=$BLACK
FOREGROUND=$WHITE
ACCENT=$GREEN
