# DARKTOOTH

# vim/bat config
SYNTAX_THEME=darktooth
AIRLINE_THEME=system
WINTERM_THEME=system

# tmux config
TMUX_THEME='system-theme'
TMUX_STATUS_BG=colour0
TMUX_STATUS_FG=colour7
TMUX_WINDOW_STATUS_BG=colour3
TMUX_WINDOW_STATUS_FG=colour1
TMUX_WINDOW_STATUS_CURRENT_BG=colour1
TMUX_WINDOW_STATUS_CURRENT_FG=colour0
TMUX_PANE_ACTIVE_BORDER=colour250
TMUX_DISPLAY_PANES_ACTIVE=colour250
TMUX_CLOCK_MODE=colour1
TMUX_WINDOW_STATUS_BELL_BG=colour9
TMUX_WINDOW_STATUS_BELL_FG=colour235
TMUX_STATUS_LEFT_BG=colour1
TMUX_STATUS_LEFT_FG=colour15
TMUX_STATUS_RIGHT_BG=colour1
TMUX_STATUS_RIGHT_FG=colour8
TMUX_STATUS_CURRENT_BG=colour1
TMUX_STATUS_CURRENT_FG=colour0

CHROME_THEME=https://chrome.google.com/webstore/detail/material-simple-dark-grey/ookepigabmicjpgfnmncjiplegcacdbm

# colors
BLACK=#282828
RED=#FB4933
GREEN=#B8BB26
YELLOW=#DD6F48
BLUE=#1B5C6B
PURPLE=#D3869B
CYAN=#66999D
WHITE=#FFFF87
BRIGHT_BLACK=#282828
BRIGHT_RED=#FB4933
BRIGHT_GREEN=#B8BB26
BRIGHT_YELLOW=#DD6F48
BRIGHT_BLUE=#1B5C6B
BRIGHT_PURPLE=#D3869B
BRIGHT_CYAN=#66999D
BRIGHT_WHITE=#FFFF87
# BRIGHT_BLACK=#7C6F64
# BRIGHT_RED=#901A1E
# BRIGHT_GREEN=#556C21
# BRIGHT_YELLOW=#FE8019
# BRIGHT_BLUE=#528B8B
# BRIGHT_PURPLE=#5FAFAF
# BRIGHT_CYAN=#83A598
# BRIGHT_WHITE=#FDF4C1

BACKGROUND=$BLACK
FOREGROUND=$WHITE
ACCENT=$RED
