# vim/bat config
SYNTAX_THEME=eva01

AIRLINE_THEME=system

# chrome config
CHROME_THEME=https://www.themebeta.com/chrome/theme/1358797

# tmux config
TMUX_THEME='system-theme'
TMUX_STATUS_BG=colour235
TMUX_STATUS_FG=colour10
TMUX_WINDOW_STATUS_BG=colour3
TMUX_WINDOW_STATUS_FG=colour8
TMUX_WINDOW_STATUS_ACTIVITY_BG=colour0
TMUX_WINDOW_STATUS_ACTIVITY_FG=colour15
TMUX_WINDOW_STATUS_CURRENT_BG=colour1
TMUX_WINDOW_STATUS_CURRENT_FG=colour0
TMUX_PANE_ACTIVE_BORDER=colour250
TMUX_PANE_BORDER=colour0
TMUX_MESSAGE_BG=colour239
TMUX_MESSAGE_FG=colour8
TMUX_MESSAGE_COMMAND_BG=colour239
TMUX_MESSAGE_COMMAND_FG=colour8
TMUX_DISPLAY_PANES_ACTIVE=colour250
TMUX_DISPLAY_PANES=colour0
TMUX_CLOCK_MODE=colour5
TMUX_WINDOW_STATUS_BELL_BG=colour9
TMUX_WINDOW_STATUS_BELL_FG=colour235
TMUX_STATUS_LEFT_BG=colour4
TMUX_STATUS_LEFT_FG=colour0
TMUX_STATUS_RIGHT_BG=colour5
TMUX_STATUS_RIGHT_FG=colour7
TMUX_STATUS_CURRENT_BG=colour3
TMUX_STATUS_CURRENT_FG=colour0

# colors
BLACK=#000000
RED=#d75f87
GREEN=#afff87
YELLOW=#dfff00
BLUE=#00ddff
PURPLE=#5f005f
CYAN=#689d6a
WHITE=#ffffff
BRIGHT_BLACK=#686868
BRIGHT_RED=#d787af
BRIGHT_GREEN=#87ff5f
BRIGHT_YELLOW=#dfff00
BRIGHT_BLUE=#afafff
BRIGHT_PURPLE=#af5fff
BRIGHT_CYAN=#875faf
BRIGHT_WHITE=#ffffff

BACKGROUND=#282828
FOREGROUND=$BRIGHT_WHITE
ACCENT=$BRIGHT_YELLOW

WALLPAPER=./wallpaper/eva01.png
WINDOWS_THEME="./windows/Eva 01.theme"
