# FAROUT

# vim/bat config
SYNTAX_THEME_PACKER=fcpg/vim-farout
SYNTAX_THEME=farout
WINTERM_THEME=system
TMUX_THEME='system-theme'

TMUX_STATUS_BG=colour8
TMUX_STATUS_FG=colour8
TMUX_WINDOW_STATUS_BG=colour3
TMUX_WINDOW_STATUS_FG=colour8
TMUX_WINDOW_STATUS_CURRENT_BG=colour1
TMUX_WINDOW_STATUS_CURRENT_FG=colour0
TMUX_PANE_ACTIVE_BORDER=colour250
TMUX_DISPLAY_PANES_ACTIVE=colour250
TMUX_CLOCK_MODE=colour4
TMUX_WINDOW_STATUS_BELL_BG=colour9
TMUX_WINDOW_STATUS_BELL_FG=colour235
TMUX_STATUS_LEFT_BG=colour1
TMUX_STATUS_LEFT_FG=colour15
TMUX_STATUS_RIGHT_BG=colour5
TMUX_STATUS_RIGHT_FG=colour8
TMUX_STATUS_CURRENT_BG=colour11
TMUX_STATUS_CURRENT_FG=colour8

# chrome config
CHROME_THEME=https://chrome.google.com/webstore/detail/dark-l20-brown/lhlhfdabjlokjmdnbclidjjdhghdgblm

# colors
BLACK=#1F1311
RED=#BF472C
GREEN=#a4896f
YELLOW=#F2A766
BLUE=#5f87af
PURPLE=#66292F
CYAN=#6B4035
WHITE=#F2DDBC

BRIGHT_BLACK=#0F0908
BRIGHT_RED=#D47D49
BRIGHT_GREEN=#A4895C
BRIGHT_YELLOW=#A67458
BRIGHT_BLUE=#a8a8a8
BRIGHT_PURPLE=#8A4B53
BRIGHT_CYAN=#A67458
BRIGHT_WHITE=#E0CCAE

BACKGROUND=$BRIGHT_BLACK
FOREGROUND=$WHITE
ACCENT=$RED

