# GRUVBOX

source ./theme/themes/gruvbox.zsh

AIRLINE_THEME=system
WINTERM_THEME=system

# segments
PROMPT_LEFT_END='\\uE0B8' # 01
PROMPT_RIGHT_START='\\uE0BA'
typeset -A SEPARATOR
set -A SEPARATOR ${(kv)SEPARATOR_SLANT}

# tmux config
TMUX_THEME='system-theme'
TMUX_STATUS_BG=colour0
TMUX_STATUS_FG=colour15
TMUX_WINDOW_STATUS_BG=colour3
TMUX_WINDOW_STATUS_FG=colour8
TMUX_WINDOW_STATUS_CURRENT_BG=colour1
TMUX_WINDOW_STATUS_CURRENT_FG=colour0
TMUX_PANE_ACTIVE_BORDER=colour250
TMUX_DISPLAY_PANES_ACTIVE=colour250
TMUX_CLOCK_MODE=colour5
TMUX_WINDOW_STATUS_BELL_BG=colour9
TMUX_WINDOW_STATUS_BELL_FG=colour235
TMUX_STATUS_LEFT_BG=colour9
TMUX_STATUS_LEFT_FG=colour0
TMUX_STATUS_RIGHT_BG=colour5
TMUX_STATUS_RIGHT_FG=colour2
TMUX_STATUS_CURRENT_BG=colour3
TMUX_STATUS_CURRENT_FG=colour0
