# HYPERLIGHT

# colors
BLACK=#2b1a38
RED=#c63a4a
GREEN=#c237c2
YELLOW=#4bbadb
BLUE=#383890
PURPLE=#745bc7
CYAN=#921487
WHITE=#fadc8a
# BRIGHT_BLACK=$BLACK
BRIGHT_BLACK=#352A3E
BRIGHT_RED=$RED
BRIGHT_GREEN=$GREEN
BRIGHT_YELLOW=$YELLOW
BRIGHT_BLUE=$BLUE
BRIGHT_PURPLE=$PURPLE
BRIGHT_CYAN=$CYAN
BRIGHT_WHITE=$WHITE

# BACKGROUND=#000000
# BACKGROUND=#1c132e
BACKGROUND=#0C041E
FOREGROUND=$BRIGHT_WHITE
ACCENT=$GREEN

# vim/bat config
SYNTAX_THEME=system
AIRLINE_THEME=system
WINTERM_THEME=system

# tmux config
TMUX_THEME='system-theme'
TMUX_STATUS_BG=$BACKGROUND
TMUX_STATUS_LEFT_BG=$RED
TMUX_STATUS_LEFT_FG=$WHITE
TMUX_STATUS_CURRENT_BG=$GREEN
TMUX_STATUS_CURRENT_FG=$BLACK
TMUX_STATUS_RIGHT_BG=$YELLOW
TMUX_STATUS_RIGHT_FG=$BLACK

# segments
# PROMPT_LEFT_END=$THEMER_EMPTY_STRING
