# colors
BLACK=#2a2426
RED=#e68183
GREEN=#87af87
YELLOW=#d9bb80
BLUE=#89beba
PURPLE=#d3a0bc
CYAN=#87c095
WHITE=#e6d6ac
BRIGHT_BLACK=#444444
BRIGHT_RED=#e39b7b
BRIGHT_GREEN=$GREEN
BRIGHT_YELLOW=$YELLOW
BRIGHT_BLUE=$BLUE
BRIGHT_PURPLE=$PURPLE
BRIGHT_CYAN=$CYAN
BRIGHT_WHITE=#d8caac

BACKGROUND=$BLACK
FOREGROUND=$WHITE
ACCENT=$BRIGHT_GREEN

WINTERM_THEME=system
SYNTAX_THEME_PLUG="'franbach/miramare'"
SYNTAX_THEME=miramare
TMUX_THEME='system-theme'

TMUX_STATUS_LEFT_BG=$BRIGHT_BLACK
TMUX_STATUS_LEFT_FG=$WHITE
TMUX_STATUS_CURRENT_BG=$RED
TMUX_STATUS_CURRENT_FG=$BLACK
TMUX_STATUS_RIGHT_BG=$GREEN
TMUX_STATUS_RIGHT_FG=$BLACK
