# MOLOKAI

# vim/bat config
SYNTAX_THEME=molokai

# chrome config
CHROME_THEME=https://chrome.google.com/webstore/detail/passion-for-pink/cogfkcjpgcgbhkllpaednchppnjepmmm?hl=en

# bpytop config
BPYTOP_THEME=monokai

# colors
BLACK=#333333
RED=#C4265E
GREEN=#86B42B
YELLOW=#B3B42B
BLUE=#6A7EC8
PURPLE=#8C6BC8
CYAN=#56ADBC
WHITE=#E3E3DD

BRIGHT_BLACK=#666666
BRIGHT_RED=#F92672
BRIGHT_GREEN=#A6E22E
BRIGHT_YELLOW=#E2E22E
BRIGHT_BLUE=#819AFF
BRIGHT_PURPLE=#AE81FF
BRIGHT_CYAN=#66D9EF
BRIGHT_WHITE=#F8F8F2

BACKGROUND=#1B1D1E
FOREGROUND=#F8F8F2
ACCENT=$BRIGHT_RED

# wallpaper (optional)
WALLPAPER=./wallpaper/hanka_gruvbox.png

