# ONE-DARK

SYNTAX_THEME_PACKER=Th3Whit3Wolf/one-nvim
SYNTAX_THEME=one-nvim

#chrome config
CHROME_THEME=https://chrome.google.com/webstore/detail/one-dark/hpkjepofpoigjlihphohlecofocheiaf?hl=en

# bpytop config
# TODO

# tmux config
TMUX_THEME='system-theme'
TMUX_STATUS_BG=colour0
TMUX_STATUS_FG=colour8
TMUX_WINDOW_STATUS_BG=colour3
TMUX_WINDOW_STATUS_FG=colour8
TMUX_WINDOW_STATUS_CURRENT_BG=colour1
TMUX_WINDOW_STATUS_CURRENT_FG=colour0
TMUX_PANE_ACTIVE_BORDER=colour250
TMUX_DISPLAY_PANES_ACTIVE=colour250
TMUX_CLOCK_MODE=colour4
TMUX_WINDOW_STATUS_BELL_BG=colour9
TMUX_WINDOW_STATUS_BELL_FG=colour235
TMUX_STATUS_LEFT_BG=colour1
TMUX_STATUS_LEFT_FG=colour15
TMUX_STATUS_RIGHT_BG=colour5
TMUX_STATUS_RIGHT_FG=colour8
TMUX_STATUS_CURRENT_BG=colour11
TMUX_STATUS_CURRENT_FG=colour8

# colors
BLACK=#282c34
RED=#e06c75
GREEN=#98c379
YELLOW=#e5c07b
BLUE=#61afef
PURPLE=#c678dd
CYAN=#56b6c2
WHITE=#abb2bf
BRIGHT_BLACK=$BLACK
BRIGHT_RED=$RED
BRIGHT_GREEN=$GREEN
BRIGHT_YELLOW=$YELLOW
BRIGHT_BLUE=$BLUE
BRIGHT_PURPLE=$PURPLE
BRIGHT_CYAN=$CYAN
BRIGHT_WHITE=$WHITE

BACKGROUND=$BLACK
FOREGROUND=$WHITE
ACCENT=$BLUE
