# RETROPUNK

BLACK=#30454b
RED=#ca6e7c
GREEN=#a0d6b1
YELLOW=#f3cbb1
BLUE=#597f89
PURPLE=#bcadd1
CYAN=#74bac1
WHITE=#f1f1f1
BRIGHT_BLACK=#7c6c5c
BRIGHT_RED=#d5617e
BRIGHT_GREEN=#bef0f9
BRIGHT_YELLOW=$YELLOW
BRIGHT_BLUE=#6c96b5
BRIGHT_PURPLE=$PURPLE
BRIGHT_CYAN=$CYAN
BRIGHT_WHITE=$WHITE

BACKGROUND=$BLACK
FOREGROUND=$WHITE
ACCENT=$YELLOW

SYNTAX_THEME=system
AIRLINE_THEME=system
WINTERM_THEME=system

# tmux config
TMUX_THEME='system-theme'
