# ROSE-PINE

# vim/bat config
SYNTAX_THEME=rose-pine-dark
AIRLINE_THEME=system
WINTERM_THEME=system

# segments
PROMPT_LEFT_START='\\uE0B6'
PROMPT_LEFT_END='\\uE0B4 '
PROMPT_RIGHT_START='\\uE0B6'
PROMPT_RIGHT_END='\\uE0B4'
LEFT_SEGMENT_START='\\uE0B4'
LEFT_SEGMENT_END='\\uE0B4'
LEFT_SEPARATOR='\\uE0B5'
RIGHT_SEGMENT_START='\\uE0B6'
RIGHT_SEGMENT_END='\\uE0B6'
RIGHT_SEPARATOR='\\uE0B7'

# tmux config
TMUX_THEME='system-theme'
TMUX_STATUS_BG=colour0
TMUX_STATUS_FG=colour8
TMUX_WINDOW_STATUS_BG=colour3
TMUX_WINDOW_STATUS_FG=colour8
TMUX_WINDOW_STATUS_CURRENT_BG=colour1
TMUX_WINDOW_STATUS_CURRENT_FG=colour0
TMUX_PANE_ACTIVE_BORDER=colour250
TMUX_DISPLAY_PANES_ACTIVE=colour250
TMUX_CLOCK_MODE=colour4
TMUX_WINDOW_STATUS_BELL_BG=colour9
TMUX_WINDOW_STATUS_BELL_FG=colour235
TMUX_STATUS_LEFT_BG=colour1
TMUX_STATUS_LEFT_FG=colour15
TMUX_STATUS_RIGHT_BG=colour5
TMUX_STATUS_RIGHT_FG=colour8
TMUX_STATUS_CURRENT_BG=colour11
TMUX_STATUS_CURRENT_FG=colour8

CHROME_THEME=https://chrome.google.com/webstore/detail/cyberpunk/ekkfihjmcoeplagmladakeignpdaecmc

# colors
BLACK=#403c58
RED=#ea6f91
GREEN=#9bced7
YELLOW=#f1ca93
BLUE=#34738e
PURPLE=#c3a5e6
CYAN=#eabbb9
WHITE=#faebd7
BRIGHT_BLACK=#6f6e85
BRIGHT_RED=#ea6f91
BRIGHT_GREEN=#9bced7
BRIGHT_YELLOW=#f1ca93
BRIGHT_BLUE=#34738e
BRIGHT_PURPLE=#c3a5e6
BRIGHT_CYAN=#eabbb9
BRIGHT_WHITE=#ffffff

BACKGROUND=#1f1d29
FOREGROUND=$WHITE
ACCENT=$BLUE
