SYNTAX_THEME=salvation
AIRLINE_THEME=salvation

HIGHLIGHT_THEME=system

TMUX_THEME='system-theme'
TMUX_STATUS_BG=colour0
TMUX_STATUS_FG=colour8
TMUX_WINDOW_STATUS_BG=colour3
TMUX_WINDOW_STATUS_FG=colour8
TMUX_WINDOW_STATUS_CURRENT_BG=colour1
TMUX_WINDOW_STATUS_CURRENT_FG=colour0
TMUX_PANE_ACTIVE_BORDER=colour250
TMUX_DISPLAY_PANES_ACTIVE=colour250
TMUX_CLOCK_MODE=colour4
TMUX_WINDOW_STATUS_BELL_BG=colour9
TMUX_WINDOW_STATUS_BELL_FG=colour235
TMUX_STATUS_LEFT_BG=colour1
TMUX_STATUS_LEFT_FG=colour15
TMUX_STATUS_RIGHT_BG=colour5
TMUX_STATUS_RIGHT_FG=colour8
TMUX_STATUS_CURRENT_BG=colour11
TMUX_STATUS_CURRENT_FG=colour8

FONT_FACE="TerminessTTF NF"
FONT_FAMILY="TerminessTTF Nerd Font"
FONT_STYLE="Normal"
FONT_SIZE=16

# highlight config
# TODO

# colors
BLACK=#1f1f1f
RED=#734541
GREEN=#5c604b
YELLOW=#8f6840
BLUE=#535c5c
PURPLE=#775759
CYAN=#775759
WHITE=#c0b18b
BRIGHT_BLACK=#4a3637
BRIGHT_RED=#734541
BRIGHT_GREEN=#63684d
BRIGHT_YELLOW=#8f6840
BRIGHT_BLUE=#535c5c
BRIGHT_PURPLE=#775759
BRIGHT_CYAN=#585c49
BRIGHT_WHITE=#978965

BACKGROUND=$BLACK
FOREGROUND=$WHITE
ACCENT=$YELLOW
