# SUNSET

# colors
BLACK=#050402
RED=#D83F1B
GREEN=#023D44
YELLOW=#FE7843
BLUE=#08737D
PURPLE=#6C3B31
CYAN=#FEA089
WHITE=#FFFEDE
BRIGHT_BLACK=#2A2A2A
BRIGHT_RED=#D83F1B
BRIGHT_GREEN=#023D44
BRIGHT_YELLOW=#FE7843
BRIGHT_BLUE=#08737D
BRIGHT_PURPLE=#6C3B31
BRIGHT_CYAN=#FEA089
BRIGHT_WHITE=#FFFEDE

# BACKGROUND=$BLACK
BACKGROUND=#0E0900
FOREGROUND=$BRIGHT_WHITE
ACCENT=$CYAN

# vim/bat config
SYNTAX_THEME=system
AIRLINE_THEME=system
WINTERM_THEME=system

#tmux config
TMUX_THEME='system-theme'

# segments
# PROMPT_LEFT_END=' \\ufb8a' # skull
PROMPT_RIGHT_START=$THEMER_EMPTY_STRING # the portion proceding user input
PROMPT_RIGHT_END=$THEMER_EMPTY_STRING # the rightmost side
LEFT_SEGMENT_START=$THEMER_EMPTY_STRING # '\\uE0B0'
LEFT_SEGMENT_END=$THEMER_EMPTY_STRING
LEFT_SEPARATOR='\\uE621' # '\\uE0B1'
RIGHT_SEGMENT_START=$THEMER_EMPTY_STRING # '\\uE0B2'
RIGHT_SEGMENT_END=$THEMER_EMPTY_STRING
RIGHT_SEPARATOR='\\uE621' # '\\uE0B3'

