# TALK

# colors
BLACK=#2b464e
RED=#963f1b
GREEN=#44946c
YELLOW=#d08c50
BLUE=#657866
PURPLE=#9f5e31
CYAN=#9d7b64
WHITE=#daaf8c
BRIGHT_BLACK=$BLACK
BRIGHT_RED=$RED
BRIGHT_GREEN=$GREEN
BRIGHT_YELLOW=$YELLOW
BRIGHT_BLUE=$BLUE
BRIGHT_PURPLE=$PURPLE
BRIGHT_CYAN=$CYAN
BRIGHT_WHITE=$WHITE

BACKGROUND=#242d2d
FOREGROUND=#f9d7ae
ACCENT=$GREEN

# vim/bat config
SYNTAX_THEME=system
AIRLINE_THEME=system
WINTERM_THEME=system

# tmux config
TMUX_THEME='system-theme'

# segments
PROMPT_LEFT_END=$THEMER_EMPTY_STRING
PROMPT_RIGHT_START=$THEMER_EMPTY_STRING # the portion proceding user input
PROMPT_RIGHT_END=$THEMER_EMPTY_STRING # the rightmost side
LEFT_SEGMENT_START=$THEMER_EMPTY_STRING # '\\uE0B0'
LEFT_SEGMENT_END=$THEMER_EMPTY_STRING
LEFT_SEPARATOR='\\uE621' # '\\uE0B1'
RIGHT_SEGMENT_START=$THEMER_EMPTY_STRING # '\\uE0B2'
RIGHT_SEGMENT_END=$THEMER_EMPTY_STRING
RIGHT_SEPARATOR='\\uE621' # '\\uE0B3'

