# TALK

# colors
# BLACK=#072e3a
BLACK=#2b464e
RED=#963f1b
GREEN=#44946c
YELLOW=#d08c50
BLUE=#657866
PURPLE=#9f5e31
CYAN=#9d7b64
WHITE=#daaf8c
BRIGHT_BLACK=#2b464e
BRIGHT_RED=#b5390f
BRIGHT_GREEN=#6f947e
BRIGHT_YELLOW=#fd9f4c
BRIGHT_BLUE=#3b5b7c
BRIGHT_PURPLE=#bc6a2c
BRIGHT_CYAN=#bfb494
BRIGHT_WHITE=#f9d7ae

BACKGROUND=#242d2d
FOREGROUND=$BRIGHT_WHITE
ACCENT=$GREEN

# vim/bat config
SYNTAX_THEME=system
AIRLINE_THEME=system
WINTERM_THEME=system

# tmux config
TMUX_THEME='system-theme'

# segments
PROMPT_LEFT_END=$THEMER_EMPTY_STRING
PROMPT_RIGHT_START=$THEMER_EMPTY_STRING # the portion proceding user input
PROMPT_RIGHT_END=$THEMER_EMPTY_STRING # the rightmost side
typeset -A SEPARATOR
set -A SEPARATOR ${(kv)SEPARATOR_BLOCK}

