# VIVID


BLACK=#1c415c
RED=#df2994
GREEN=#25c009
YELLOW=#f0920a
BLUE=#15bee7
PURPLE=#7343c9
CYAN=#87dce6
WHITE=#cdd5e0
BRIGHT_BLACK=#727c6f
BRIGHT_RED=$RED
BRIGHT_GREEN=$GREEN
BRIGHT_YELLOW=$YELLOW
BRIGHT_BLUE=$BLUE
BRIGHT_PURPLE=$PURPLE
BRIGHT_CYAN=$CYAN
BRIGHT_WHITE=$WHITE

BACKGROUND=#0f1b2b
FOREGROUND=$WHITE
ACCENT=$RED

# vim/bat config
SYNTAX_THEME=system
AIRLINE_THEME=system
WINTERM_THEME=system

# tmux config
TMUX_THEME='system-theme'
TMUX_STATUS_BG=$BACKGROUND
TMUX_STATUS_LEFT_BG=$RED
TMUX_STATUS_LEFT_FG=$WHITE
TMUX_STATUS_CURRENT_BG=$GREEN
TMUX_STATUS_CURRENT_FG=$BLACK
TMUX_STATUS_RIGHT_BG=$YELLOW
TMUX_STATUS_RIGHT_FG=$BLACK
