# ZENBURN

# vim/bat config
SYNTAX_THEME=zenburn
AIRLINE_THEME=system
WINTERM_THEME=system

# tmux config
TMUX_THEME='system-theme'
TMUX_STATUS_BG=colour0
TMUX_STATUS_FG=colour8
TMUX_WINDOW_STATUS_BG=colour3
TMUX_WINDOW_STATUS_FG=colour8
TMUX_WINDOW_STATUS_CURRENT_BG=colour1
TMUX_WINDOW_STATUS_CURRENT_FG=colour0
TMUX_PANE_ACTIVE_BORDER=colour250
TMUX_DISPLAY_PANES_ACTIVE=colour250
TMUX_CLOCK_MODE=colour4
TMUX_WINDOW_STATUS_BELL_BG=colour9
TMUX_WINDOW_STATUS_BELL_FG=colour235
TMUX_STATUS_LEFT_BG=colour1
TMUX_STATUS_LEFT_FG=colour15
TMUX_STATUS_RIGHT_BG=colour5
TMUX_STATUS_RIGHT_FG=colour8
TMUX_STATUS_CURRENT_BG=colour11
TMUX_STATUS_CURRENT_FG=colour8

CHROME_THEME=https://chrome.google.com/webstore/detail/cyberpunk/ekkfihjmcoeplagmladakeignpdaecmc

# colors
BLACK=#3F3F3F
RED=#705050
GREEN=#60B48A
YELLOW=#DFAF8F
BLUE=#506070
PURPLE=#DC8CC3
CYAN=#8CD0D3
WHITE=#DCDCCC
BRIGHT_BLACK=#709080
BRIGHT_RED=#DCA3A3
BRIGHT_GREEN=#C3BF9F
BRIGHT_YELLOW=#F0DFAF
BRIGHT_BLUE=#94BFF3
BRIGHT_PURPLE=#EC93D3
BRIGHT_CYAN=#93E0E3
BRIGHT_WHITE=#DCDCCC

BACKGROUND=$BLACK
FOREGROUND=$WHITE
ACCENT=$GREEN
