-- activate plugin configurations
require('./config/aerial')
require('./config/autopairs')
require('./config/autotag')
require('./config/bufferline')
require('./config/colorizer')
require('./config/compe')
require('./config/diffview')
require('./config/fterm')
require('./config/galaxyline')
require('./config/gitsigns')
-- require('./config/lightspeed')
require('./config/lspconfig')
require('./config/lsp-kind')
require('./config/lsp-signature')
require('./config/neorg')
-- require('./config/neoscroll')
require('./config/shade')
require('./config/spectre')
-- require('./config/surround')
require('./config/symbols-outline')
require('./config/telescope')
require('./config/treesitter')

